controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'hello.html.twig'


app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Controller\SecurityController::displayRegister
  methods: [GET]

register_user:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: ['POST']

users:
  path: /users
  controller: App\Controller\UserController::index
  methods: [GET]


roles:
  path: /roles
  controller: App\Controller\RoleController::index
  methods: [GET]

role_edit:
  path: /role_edit/{id}
  controller: App\Controller\RoleController::edit
  methods: [GET, POST]

role_update:
  path: /role_update/{id}
  controller: App\Controller\RoleController::edit
  methods: [PUT]

role_delete:
  path: /role_delete/{id}
  controller: App\Controller\RoleController::destory
  methods: [DELETE]


categories:
  path: /categories
  controller: App\Controller\CategoryController::index
  methods: [GET]

category_edit:
  path: /category_edit/{id}
  controller: App\Controller\CategoryController::edit
  methods: [GET, POST]

category_update:
  path: /category_update/{id}
  controller: App\Controller\CategoryController::edit
  methods: [PUT]

category_delete:
  path: /category_delete/{id}
  controller: App\Controller\CategoryController::destory
  methods: [DELETE]


role_create:
  path: /role_create
  controller: App\Controller\RoleController::create
  methods: [GET, POST]

products:
  path: /products
  controller: App\Controller\ProductController::index
  methods: [GET]

product_edit:
  path: /product_edit/{id}
  controller: App\Controller\ProductController::edit
  methods: [GET, POST]

product_update:
  path: /product_update/{id}
  controller: App\Controller\ProductController::edit
  methods: [PUT]

product_delete:
  path: /product_delete/{id}
  controller: App\Controller\ProductController::destory
  methods: [DELETE,POST]


permission_create:
  path: /permission_create
  controller: App\Controller\PermissionController::create
  methods: [GET, POST]
  
permissions:
  path: /permissions
  controller: App\Controller\PermissionController::index
  methods: [GET]

permission_edit:
  path: /permission_edit/{id}
  controller: App\Controller\PermissionController::edit
  methods: [GET, POST]

permission_update:
  path: /permission_update/{id}
  controller: App\Controller\PermissionController::edit
  methods: [PUT]

permission_delete:
  path: /permission_delete/{id}
  controller: App\Controller\PermissionController::destroy
  methods: [DELETE,POST]
